name: Start new voting epoch

on:
    workflow_dispatch:
        inputs:
            beets_to_distribute:
                description: 'The amounts of BEETS to distribute'
                require: true

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    initEpoch:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install deps
              run: bun install --frozen-lockfile

            - name: Inititalize new epoch
              env:
                  BEETS_TO_DISTRIBUTE: ${{ github.event.inputs.beets_to_distribute }}
              run: bun ts-node ./src/inititalizeRound.ts

            - name: Create PR
              uses: peter-evans/create-pull-request@v5
              with:
                  commit-message: 'Inititalize new gauge epoch'
                  title: 'Inititalize new gauge epoch with ${{ github.event.inputs.beets_to_distribute }} BEETS'
                  assignees: franzns
                  branch: init-gauge-round
                  delete-branch: true
                  labels: 'Automated PR'
